### ISSUE TITLE
Don't show hidden API in api-docs and remove dupes

### ISSUE THREAD

**Issue by Peter9192** [AI4S2S/lilio#19]
The api docs include hidden modules such as `_plot` (e.g. https://lilio--18.org.readthedocs.build/en/18/autoapi/lilio/_plot/index.html).

Furthermore, it shows both the functions exposed through `__init__.py` and from where they're imported, resulting in duplicate API docs for e.g. `lilio.Calendar` and `lilio.calendar.Calendar`.

**Comment by BSchilperoort** [comment]
Well spotted. I'll see if I can figure out how to remove the dupes.

Hiding private functions seems to be easy (https://sphinx-autoapi.readthedocs.io/en/latest/reference/config.html#customisation-options).

I have noticed now though, that we need to then rename `_resample.py` to `resample.py`, and make all functions in that file (except resample) private. Otherwise `resample` won't be in the API docs, as it's included into lilio through `__init__.py`.

**Comment by BSchilperoort** [comment]
This is fixed now. No more dupes, and no private functions are visible anymore!

I did just notice that the examples in the API reference of lilio are broken (lack of empty lines between text and code blocks `>>>`):
https://lilio.readthedocs.io/en/latest/autoapi/lilio/index.html
But I included a fix in #28.
